services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api/app:/app/app

    env_file:
      - ./.env.local

    environment:
      TUNAGU_CORS_ORIGINS: "*"

    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload